# Generated by Django 4.0.6 on 2022-07-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر')),
                ('drafted', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیش نویس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('p', 'انتشار یافته'), ('d', 'پیش نویس'), ('i', 'در انتظار انتشار'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
